server:
  port: 8082

spring:
  application:
    name: job-posting-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/job_recommendations
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
