server:
  port: 8081

spring:
  application:
    name: recommendation-service
    bootstrap-servers: localhost:29092
    consumer:
      group-id: recommendation-group
      auto-offset-reset: earliest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  model:
    path: models/recommendation-model.zip
